version: '3.8'

services:
  frontend:
    build:
      context: ./employee-management-frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./employee-management-api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - management-service
    environment:
      - GRPC_SERVER=management-service:50051

  management-service:
    build:
      context: ./employee-management-service
    ports:
      - "50051:50051"
    environment:
      - DATABASE_URL=postgres://username:password@db:5432/employees_db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employees_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
